### ISSUE TITLE
Update Expo v46

### ISSUE THREAD

**Issue by jorgeruvalcaba** [calitb/expo-e2e-demo#7]
Any plan to update the example?

**Comment by calitb** [comment]
yep, I can look into it.

If you use EAS services you can run the e2e in there too https://docs.expo.dev/build-reference/e2e-tests/ . I'll try to update the example with this too.

**Comment by calitb** [comment]
updated codebase to sdk46

and added automation to run e2e using EAS servers https://github.com/calitb/expo-e2e-demo/commit/182924248976533cf71bb33817f4dbc98a62c922
